<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <title>listar Usuarios</title>
</head>
<body>
<h4>Clientes Listados</h4>
    <div class="container">
        <div class="table responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id Usuario</th>
                        <th>Nombre Usuario</th>
                        <th>Apellido Paterno</th>
                        <th>Apellido Materno</t<h>
                        <th>Edad</t<h>
                    </tr>
                </thead>
                <tbody id="DataResult">

                </tbody>
            </table>
            <a href="#">
            </a>
            <input type="submit" class="btn btn-success" onclick="v()" value="Agregar nuevo Cliente">
        </div>
    </div>
	<script>

function v(){
    $.ajax({
       url: 'Controllers/usuarios_controller.php',
       //url: '../hola.php'
       type: "POST",
       data: {
           'c' : 'Consultar'
     },
     //dataType: "JSON",
       success: function(data) {
         console.log(data);//alert(data);
         /*var html = '';
         var i;
         for (i = 0; i < data.length; i++) {
           html += '<tr>' +
             '<td>' + data[i].idUsuario + '</td>' +
             '<td>' + data[i].nombreUsuario + '</td>' +
             '<td>' + data[i].apellidoPaternoUsuario + '</td>' +
             '<td>' + data[i].apellidoMaternoUsuario + '</td>' +
             '<td>' + data[i].edadUsuario + '</td>' +
             '</tr>';
         }
         $('#DataResult').html(html);*/
       },
       error: function(jqXHR, textStatus, errorThrown) {
         alert('Error...');
       }
     });

}


$(document).ready(function(){
    $.ajax({
       url: 'Controllers/usuarios_controller.php',
       //url: '../hola.php'
       type: "POST",
       data: {
           'c' : 'Consultar'
     },
     //dataType: "JSON",
       success: function(data) {
         console.log(data);//alert(data);
         /*var html = '';
         var i;
         for (i = 0; i < data.length; i++) {
           html += '<tr>' +
             '<td>' + data[i].idUsuario + '</td>' +
             '<td>' + data[i].nombreUsuario + '</td>' +
             '<td>' + data[i].apellidoPaternoUsuario + '</td>' +
             '<td>' + data[i].apellidoMaternoUsuario + '</td>' +
             '<td>' + data[i].edadUsuario + '</td>' +
             '</tr>';
         }
         $('#DataResult').html(html);*/
       },
       error: function(jqXHR, textStatus, errorThrown) {
         alert('Error...');
       }
     });
})
    </script>
</body>
</html>
